export enum Command {
  Interact = 'interact',
  Inventory = 'i',
  Map = 'm',
  Journal = 'j',
  Talk = 'talk',
  DoNothing = '',
  MoveUp = 'w',
  MoveDown = 's',
  MoveRight = 'd',
  MoveLeft = 'a',
  MoveUpRight = 'wd',
  MoveUpLeft = 'wq',
  MoveDownRight = 'sd',
  MoveDownLeft = 'sa',
}
